#!/bin/bash

sudo apt-get -y install git
sudo apt-get -y install python-dev
sudo apt-get -y install gcc
sudo apt-get -y install make
sudo apt-get -y install python-pip
sudo apt-get -y install libxml2-dev libxslt-dev zlib1g-dev
sudo pip install greenlet
sudo pip install Flask
sudo pip install beautifulsoup4
sudo pip install lxml
sudo pip install gevent


